accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'auth'

urlpatterns = [
	path('signup/', views.sign_up, name='sign_up'),
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from notes import urls as note_urls
from accounts import urls as auth_urls

urlpatterns = [
    path('', include(note_urls)),
    path('auth/', include(auth_urls)),
    path('admin/', admin.site.urls),
]

notes/urls.py
from django.urls import path
from notes import views

app_name = 'notes'

urlpatterns = [
	path('', views.home, name='home'),
	path('notes/new/', views.new_note, name='new_note'),
	path('notes/<int:pk>/', views.note_detail, name='note_detail')
]

accounts/models.py
from django.db import models

# Create your models here.

notes/models.py
from django.db import models
from django.contrib.auth.models import User

class Note(models.Model):
	COLOR_CHOICES = [
		('RED', 'red'),
		('BLU', 'blue'),
		('YEL', 'yellow'),
		('ORA', 'orange'),
		('GRE', 'green'),
		('PUR', 'purple'),
		('BRO', 'brown'),
		('FUX', 'fuxia')
	]

	content = models.TextField(max_length=350)
	user = models.ForeignKey(User, related_name='notes', on_delete=models.CASCADE)
	date_added = models.DateTimeField(auto_now_add=True)
	color = models.CharField(max_length=10, choices=COLOR_CHOICES, default='yellow')

	def __str__(self):
		return f"{self.user.username}'s note no. {self.pk}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	email = forms.TextInput()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

notes/forms.py
from django import forms
from notes.models import Note

class NoteForm(forms.ModelForm):
	color = forms.Select()

	class Meta:
		model = Note
		fields = ['content', 'color']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login

from accounts.forms import SignUpForm

def sign_up(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect('notes:home')
	else:
		form = SignUpForm()

	return render(request, 'accounts/sign_up.html', {'form': form})

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from notes.models import Note
from notes.forms import NoteForm

@login_required
def home(request):
	user = request.user
	notes = user.notes.all()
	return render(request, 'notes/home.html', {'notes': notes})

@login_required
def new_note(request):
	if request.method == 'POST':
		form = NoteForm(request.POST)
		if form.is_valid():
			note = form.save(commit=False)
			note.user = request.user
			note.save()
			return redirect('notes:home')
	else:
		form = NoteForm()

	return render(request, 'notes/new_note.html', {'form': form})

@login_required
def note_detail(request, pk):
	user = request.user
	note = get_object_or_404(Note, pk=pk)
	if note.user == user:
		return render(request, 'notes/note_detail.html', {'note': note})

	return redirect('notes:home')

templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}{% endblock title %}</title>
		<link rel="stylesheet" href="{% static "css/bulma.min.css" %}">
		<link rel="stylesheet" href="{% static "css/accounts.css" %}">
		<link rel="stylesheet" href="{% static "css/base.css" %}">
	</head>

	<body>
		<div class="columns is-centered is-vcentered is-fullheight">
			<div class="column is-4">
				<div class="card mb-2 has-text-left">
					<header class="card-header">
						<p class="card-header-title py-2">
							{% block card-header %}
								
							{% endblock card-header %}
						</p>
					</header>

					<div class="card-content px-3 py-3">
						{% block body %}
							
						{% endblock body %}
					</div>
				</div>

				<small class="has-text-centered is-block">
					{% block card-footer %}
								
					{% endblock card-footer %}
				</small>
			</div>
		</div>
		<script src="{% static "js/bulma/bulma.js" %}"></script>
	</body>
</html>

templates/accounts/login.html
{% extends "accounts/base.html" %}
{% load widget_tweaks %}

{% block title %}
	Log in
{% endblock title %}

{% block card-header %}
	Log in
{% endblock card-header %}

{% block body %}
	<form method="POST" novalidate>
		{% csrf_token %}
		{% for field in form %}
			<div class="field">
				<label class="label is-small">{{ field.label }}</label>
				{% render_field field class="input" placeholder=field.name %}
			</div>
		{% endfor %}
		<button type="submit" class="button is-primary is-fullwidth">log in</button>
	</form>
{% endblock body %}

{% block card-footer %}
	Don't have an account? Sign up 
	<a href="{% url 'auth:sign_up' %}">here</a>.
{% endblock card-footer %}

templates/accounts/sign_up.html
{% extends "accounts/base.html" %}
{% load widget_tweaks %}

{% block title %}
	Sign up
{% endblock title %}

{% block card-header %}
	Sign up
{% endblock card-header %}

{% block body %}
	<form method="POST" novalidate>
		{% csrf_token %}
		{% for field in form %}
			<div class="field">
				<label class="label is-small">{{ field.label }}</label>
				{% render_field field class="input" %}
			</div>
		{% endfor %}
		<button type="submit" class="button is-primary is-fullwidth">sign up</button>
	</form>
{% endblock body %}

{% block card-footer %}
	Already have an account? Log in 
	<a href="{% url 'auth:login' %}">here</a>.
{% endblock card-footer %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}{% endblock title %}</title>
		<link rel="stylesheet" href="{% static "css/bulma.min.css" %}">
		<link rel="stylesheet" href="{% static "css/base.css" %}">
	</head>
	<body>
		{% block body %}
			
		{% endblock body %}
		<script src='{% static "js/bulma/bulma.js" %}'></script>
	</body>
</html>

templates/notes/home.html
{% extends "base.html" %}

{% block title %}
	Your notes
{% endblock title %}

{% block body %}
	<ul>
		{% for note in notes %}
			<li>
				<a href="#">{{ note }}</a>
			</li>
		{% endfor %}
	</ul>
{% endblock body %}

templates/notes/new_note.html
{% extends "base.html" %}

{% block title %}
	Create a new note
{% endblock title %}

{% block body %}
	<h1>Add a new note</h1>
	<form method="post" novalidate>
			{% csrf_token %}
			{{ form.as_p }}
		<button type="submit">Add</button>
	</form>
{% endblock body %}

templates/notes/note_detail.html
{% extends "base.html" %}

{% block title %}
	Your note
{% endblock title %}

{% block body %}
	<p>{{ note.content }}</p>
{% endblock body %}